<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 3: Web API and NLP

--- 
# Contents


---

### Contents:
Notebook 2
- [Part3](#Part3)
    - Importing Library
    - Load CSV files
    - Data Cleaning
        - Function for removing https, special characters, terms and digits in the title and selftext
        - Understanding features
            - Whiskey
            - Rum
        - Feature engineering
            - Removing features for Whiskey
            - Removing features for Rum
            - Combine both Whiskey and Rum dataframe

--- 
# Part 3
Cleaning data

---

## 3.1 Importing library

In [3]:
import pandas as pd
import datetime as dt
import numpy as np
import re

In [4]:
pd.set_option('display.max_columns', 4000)
pd.set_option('display.max_rows', 4000)

## 3.2 Load csv files

In [5]:
whiskey = pd.read_csv('../datasets/whiskey.csv')
rum = pd.read_csv ('../datasets/rum.csv')

## 3.3 Data cleaning

In [6]:
#checking
whiskey.head(1)

,author,id,score,subreddit,title,selftext,num_comments,timestamp
0,metdthero,vhz4az,1,whiskey,Facts and Truth,NaN,0,2022-06-22 15:11:17

In [7]:
#checking
rum.head(1)

,author,id,score,subreddit,title,selftext,num_comments,timestamp
0,TRFKTA,vi2mrr,1,rum,Out shopping for Rum and came across this. The...,NaN,0,2022-06-22 19:05:31

### 3.3.1 Function for removing https, special characters, terms and digits in the title and selftext

In [93]:
#remove any URLs in selftext and title for whiskey and rum,
#found special characters and urls in later result

def regex_cleaning(row):
        
    # Remove links
    row['selftext'] = re.sub(
        pattern=r'\w+:\/\/[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*', 
        repl='', 
        string=row['selftext'],
        flags=re.M)
    row['title'] = re.sub(
        pattern=r'\w+:\/\/[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*', 
        repl='', 
        string=row['title'],
        flags=re.M)
    
    # Remove special terms    
    row['selftext'] = re.sub(
        pattern='#x200B;|&lt;|&gt;|&amp;|_',
        repl='',
        string=row['selftext'])
    row['title'] = re.sub(
        pattern='#x200B;|&lt;|&gt;|&amp;|_',
        repl='',
        string=row['title'])
    
    # Remove all digits
    row['selftext'] = re.sub(
        pattern=r'\d+',
        repl='',
        string=row['selftext'])
    row['title'] = re.sub(
        pattern=r'\d+',
        repl='',
        string=row['title'])
    
    # Remove anything that is not a word
    row['selftext'] = re.sub(
        pattern=r'\W+',
        repl=' ',
        string=row['selftext'])
    row['title'] = re.sub(
        pattern=r'\W+',
        repl=' ',
        string=row['title'])

    return row

### 3.3.2 Understanding features

In [94]:
#checking for null values
whiskey.isnull().sum()

author             0
id                 0
score              0
subreddit          0
title              0
selftext        6324
num_comments       0
timestamp          0
dtype: int64

In [95]:
rum.isnull().sum()

author             0
id                 0
score              0
subreddit          0
title              0
selftext        4683
num_comments       0
timestamp          0
dtype: int64

In [96]:
def valuecounts (dataframe):
    for column in dataframe:
        print(dataframe[column].value_counts())
        
def describe (dataframe):
    for column in dataframe:
        print(dataframe[column].describe())

#### 3.3.2.1 Whiskey

In [97]:
valuecounts(whiskey)

[deleted]           580
winetimes            38
petermal67           35
irish56_ak           31
Neversafeforlife     23
                   ...
myballsaresweaty      1
WhiskyIsRisky         1
narambula25           1
doown_                1
Fishermichaels        1
Name: author, Length: 7289, dtype: int64
vhz4az    1
5wbxy1    1
5w6d2e    1
5w6k63    1
5w6kxb    1
         ..
dtpbtz    1
dtpots    1
dtpoyp    1
dtq79u    1
24qhyh    1
Name: id, Length: 9842, dtype: int64
1       4561
0        603
2        460
3        351
4        272
5        269
6        247
7        209
8        203
9        185
10       168
11       142
12       137
13       110
15        99
16        94
14        87
18        71
19        69
17        64
21        63
23        57
20        57
25        50
28        44
24        42
27        40
26        38
30        37
38        31
31        30
34        29
22        27
32        24
37        23
40        22
43        21
35        21
45        21
29        21
49        19
52        18
33        18
68        17
61        17
36        17
39        17
55        15
63        14
48        14
42        14
54        14
51        13
46        13
59        12
60        12
72        12
44        12
41        12
75        12
47        11
57        11
50        10
58        10
69        10
91         9
64         8
53         8
87         8
67         8
66         8
62         8
71         7
78         6
121        6
89         6
81         6
70         6
98         6
85         6
96         5
82         5
80         5
93         5
120        4
116        4
74         4
79         4
76         4
56         4
101        4
92         4
125        4
146        4
84         4
151        3
194        3
86         3
65         3
108        3
106        3
88         3
265        3
198        3
212        3
102        3
113        3
122        3
130        3
129        3
189        3
73         3
183        3
134        3
109        3
148        3
107        3
77         3
226        2
170        2
453        2
126        2
200        2
90         2
245        2
137        2
155        2
117        2
164        2
263        2
153        2
158        2
176        2
127        2
100        2
177        2
123        2
141        2
110        2
215        2
193        2
95         2
103        2
132        2
83         2
240        1
190        1
135        1
188        1
94         1
115        1
112        1
178        1
140        1
222        1
219        1
99         1
213        1
111        1
210        1
227        1
136        1
131        1
118        1
249        1
162        1
662        1
149        1
201        1
211        1
230        1
165        1
406        1
197        1
138        1
381        1
380        1
247        1
191        1
169        1
220        1
244        1
152        1
217        1
294        1
338        1
282        1
228        1
384        1
206        1
345        1
257        1
255        1
277        1
239        1
383        1
357        1
172        1
682        1
288        1
1369       1
289        1
1247       1
1729       1
281        1
166        1
619        1
258        1
813        1
143        1
204        1
196        1
1290       1
361        1
638        1
604        1
248        1
209        1
696        1
150        1
124        1
144        1
343        1
358        1
296        1
173        1
456        1
97         1
283        1
214        1
187        1
184        1
203        1
267        1
301        1
279        1
287        1
385        1
677        1
303        1
499        1
544        1
232        1
273        1
147        1
546        1
347        1
299        1
461        1
669        1
128        1
Name: score, dtype: int64
whiskey    9842
Name: subreddit, dtype: int64
Japanese whiskey                                                                                                5
My collection so far                                                                                            5
Whiskey                                                                                                         4
Little Robin beauty! If money was no object.....                                                                3
New to whiskey                                                                                                  3
                                                                                                               ..
This was a hard one to finish off. Since I don't live in Texas, I may never see another bottle in real life.    1
Skrewball Peanut Butter Whiskey                                                                                 1
So just bought Jack Daniels Single Barrel Select, and I love it. Is the barrel proof worth $30 more though?     1
I'm a fairly new whiskey drinker (about 1 year). What was your guys' first whiskey? Mine was Crown Royal.       1
Reddit detectives of /r/whiskey, how old is this whiskey I just drank?                                          1
Name: title, Length: 9711, dtype: int64

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [98]:
whiskey['selftext'].value_counts(sort=True, ascending=False).head()

[deleted]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  339
[removed]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  112
Can someone point me to any time graphs - or raw data - showing growth in US and worldwide demand for distilled spirits over the last 20 years, and projections for future growth?\n\nI'm also trying to find what has been pricing for wholesale distilled spirits in the same timeframe, and projected forward.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2
My father passed away in 2006, he had stopped drinking shortly after returning from Vietnam,  but that didn't stop people from gifting him bottles. \n\nSo, while cleaning the host post-wake, we found two bottles of Drambuie, one opened and slightly touched, the other still sealed.  The opened one was disposed of, but I kept the sealed bottle just because. \n\nI figure its most likely from the 80s. \n\nAlcohol and my family are not great friends. In fact its only my maternal grandmother and myself who decided to make a living (of sorts) of it, everyone else is an amateur or a professional. \n\nSo is a, probably,  40 year old ,sealed bottle of Drambuie going to be safe for toasts for what would have been Dads 100th birthday in 5 years?  I'm a brewer, I don't know jack about aging liqueur or whatnot      1
Any recommendations on stuff to try while in Bangkok? Thanks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Name: selftext, dtype: int64

In [99]:
whiskey['num_comments'].value_counts()

0      1811
1       761
2       618
4       596
3       559
5       551
6       481
7       421
8       386
9       376
10      334
11      274
12      241
13      196
14      194
15      185
16      174
18      147
17      135
20      107
19      103
21       90
22       87
23       83
26       70
24       56
25       55
27       54
28       44
31       41
30       40
33       36
34       35
29       32
32       31
36       29
37       28
38       27
35       19
42       18
41       16
43       15
40       15
39       13
50       11
46       11
49       11
45       10
47        9
57        9
44        8
59        8
53        8
52        7
54        6
60        6
66        6
61        6
65        6
55        6
81        5
48        5
63        5
75        5
62        5
67        5
79        4
58        4
68        4
96        4
70        4
51        4
56        3
77        3
78        3
104       3
84        3
91        3
72        3
76        3
105       2
71        2
114       2
64        2
98        2
95        2
92        2
74        2
112       2
87        2
69        2
80        1
131       1
94        1
99        1
122       1
162       1
246       1
85        1
139       1
190       1
118       1
177       1
228       1
88        1
93        1
117       1
134       1
73        1
153       1
129       1
269       1
82        1
116       1
102       1
126       1
167       1
160       1
140       1
107       1
187       1
Name: num_comments, dtype: int64

In [100]:
whiskey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9842 entries, 0 to 9841
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   author        9842 non-null   object
 1   id            9842 non-null   object
 2   score         9842 non-null   int64
 3   subreddit     9842 non-null   object
 4   title         9842 non-null   object
 5   selftext      3518 non-null   object
 6   num_comments  9842 non-null   int64
 7   timestamp     9842 non-null   object
dtypes: int64(2), object(6)
memory usage: 615.2+ KB

In [101]:
describe(whiskey)

count          9842
unique         7289
top       [deleted]
freq            580
Name: author, dtype: object
count       9842
unique      9842
top       vhz4az
freq           1
Name: id, dtype: object
count    9842.000000
mean       13.606482
std        48.390404
min         0.000000
25%         1.000000
50%         1.000000
75%        10.000000
max      1729.000000
Name: score, dtype: float64
count        9842
unique          1
top       whiskey
freq         9842
Name: subreddit, dtype: object
count                 9842
unique                9711
top       Japanese whiskey
freq                     5
Name: title, dtype: object
count          3518
unique         3068
top       [deleted]
freq            339
Name: selftext, dtype: object
count    9842.000000
mean        9.681772
std        14.314444
min         0.000000
25%         1.000000
50%         6.000000
75%        12.000000
max       269.000000
Name: num_comments, dtype: float64
count                    9842
unique                   9842
top       2022-06-22 15:11:17
freq                        1
Name: timestamp, dtype: object

In [102]:
whiskey.shape

(9842, 8)

#### 3.3.2.2 Rum

In [103]:
valuecounts(rum)

[deleted]           244
thefatrumpirate     124
anax44               99
LIFOanAccountant     86
t8ke                 79
                   ...
marcoporras           1
LLbeejay              1
josmoize              1
MattChap              1
shardmonkey           1
Name: author, Length: 4150, dtype: int64
vi2mrr    1
7soi5q    1
7shegz    1
7sg24v    1
7sfpf0    1
         ..
geo4me    1
ge9yuj    1
ge9tr5    1
ge93u9    1
24o3yr    1
Name: id, Length: 7849, dtype: int64
1      4131
2       306
3       288
6       243
5       240
7       229
4       220
8       191
0       159
9       152
10      137
11      125
12      118
13      108
14       80
16       76
17       73
15       70
18       67
19       60
20       53
21       45
23       45
24       41
26       40
22       40
28       32
29       27
25       25
32       25
27       25
30       24
34       22
31       21
35       20
41       18
37       14
40       13
43       13
39       11
36       11
42       11
48       10
44       10
33       10
55        9
38        9
52        9
61        8
57        8
46        7
47        7
62        6
45        6
63        5
54        5
58        5
49        4
59        4
86        4
64        4
50        4
70        3
72        3
68        3
53        3
67        3
51        3
77        3
80        3
82        3
56        2
71        2
65        2
112       2
79        2
95        2
88        2
75        2
73        2
83        2
85        1
108       1
74        1
92        1
166       1
69        1
103       1
84        1
105       1
93        1
66        1
149       1
76        1
113       1
91        1
119       1
87        1
136       1
60        1
Name: score, dtype: int64
rum    7849
Name: subreddit, dtype: int64
Monthly Astor Pick Ups                                                                                                         4
My collection                                                                                                                  4
My Rum Collection                                                                                                              4
My humble collection                                                                                                           4
Eldorado 21                                                                                                                    4
                                                                                                                              ..
I’m going to the beach soon. Best rum to have with Coke while there?                                                           1
Appleton Estate Cocktails???                                                                                                   1
Any opinions on this rum I bought.                                                                                             1
Is there any kind person out there willing to ship me some Ron De Jeremy XO? Not available in the US.. I’ll pay for it all!    1
First bottle of rum I bought. I've found my new favourite liquor. What are some of the must try with rum?                      1
Name: title, Length: 7696, dtype: int64

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [104]:
rum['selftext'].value_counts(sort=True, ascending=False).head()

[removed]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             348
[deleted]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             138
Last night I had some Diplomatico Reserva (non-exclusiva) for the first time. This morning I feel like crap. I've read that they add a lot of sugar. Could that impact the hangover feel or do I just need to drink more water?                                                                                                                                                                                                                                                                         2
im traveling to cuba in august and want to bring back the most and best rum i can find. from what i have researched i understand that you can bring back 100$ worth of rum or cigars back. is that without declaring it or in general? has anything changed at all since that rule was made? if not, what is the best bang-for-my-buck rum i should get while im there and maybe a few must-haves that you guys reccomend. want to come home with at least three bottles, and at most six. thanks!      2
Nope.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   2
Name: selftext, dtype: int64

In [105]:
rum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7849 entries, 0 to 7848
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   author        7849 non-null   object
 1   id            7849 non-null   object
 2   score         7849 non-null   int64
 3   subreddit     7849 non-null   object
 4   title         7849 non-null   object
 5   selftext      3166 non-null   object
 6   num_comments  7849 non-null   int64
 7   timestamp     7849 non-null   object
dtypes: int64(2), object(6)
memory usage: 490.7+ KB

In [106]:
describe(rum)

count          7849
unique         4150
top       [deleted]
freq            244
Name: author, dtype: object
count       7849
unique      7849
top       vi2mrr
freq           1
Name: id, dtype: object
count    7849.000000
mean        6.953115
std        12.223031
min         0.000000
25%         1.000000
50%         1.000000
75%         8.000000
max       166.000000
Name: score, dtype: float64
count     7849
unique       1
top        rum
freq      7849
Name: subreddit, dtype: object
count                       7849
unique                      7696
top       Monthly Astor Pick Ups
freq                           4
Name: title, dtype: object
count          3166
unique         2677
top       [removed]
freq            348
Name: selftext, dtype: object
count    7849.000000
mean        8.670149
std        10.894061
min         0.000000
25%         1.000000
50%         6.000000
75%        12.000000
max       231.000000
Name: num_comments, dtype: float64
count                    7849
unique                   7846
top       2022-03-29 23:12:00
freq                        2
Name: timestamp, dtype: object

In [107]:
rum.shape

(7849, 8)

Feature key points:  
  
1.**author** is norminal feature, value delete occur if user deleted the account.  
author 590 deleted for whiskey and 246 deleted for rum.  
  
2.**id** is a norminal feature string attached to each user  
  
3.**score** is a discrete feature  
  
4.**title** is norminal feature  
  
5.**selftext** is a norminal feature  
there are removed and deleted in selftext
  
6.**num_comments** is the number of comments, discrete feature  
  
7.**timestamp** is a continuous data feature

### 3.3.3 Feature engineering

#### 3.3.3.1 Whiskey removal of columns

In [108]:
whiskey1 = whiskey[['title', 'selftext']]
whiskey1.head()

,title,selftext
0,Facts and Truth,NaN
1,Dads old bottles.,"My father passed away in 2006, he had stopped ..."
2,Key West Bourbon Whiskey. Was it a mistake,NaN
3,I picked up High West Double Rye Barrel Select...,NaN
4,Review #32: Green Spot,NaN

In [109]:
#remove duplicates
whiskey1.drop_duplicates(keep="first", inplace=True)

C:\Users\Jing Cheng\AppData\Local\Temp\ipykernel_10860\710209946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  whiskey1.drop_duplicates(keep="first", inplace=True)

In [110]:
# remove all null, removed or deleted in dataframe, replace nan with empty string
whiskey1 = whiskey1.replace({"[removed]": np.NaN})
whiskey1 = whiskey1.replace({"[deleted]": np.NaN})
whiskey1 = whiskey1.replace(np.nan, "", regex=True)

In [111]:
#clean the titles and selftext before combining
whiskey1 = whiskey1.apply(regex_cleaning, axis=1)

In [112]:
#labelling each row in whiskey; 1 
whiskey1['origin'] = 1

In [113]:
#combine selftext and title to form a new column alltext
whiskey1['alltext'] = whiskey1['title'] + " " + whiskey1['selftext']

In [114]:
whiskey1.shape

(9765, 4)

#### 3.3.3.2 Rum removal of columns

In [115]:
rum1 = rum[['title', 'selftext']]
rum1.head()

,title,selftext
0,Out shopping for Rum and came across this. The...,NaN
1,Most expensive bottle of rum I've personally c...,&amp;#x200B;\n\nhttps://preview.redd.it/rbvf9o...
2,Appleton Estate 21,"Hey all,\n\nI picked up two bottles of Appleto..."
3,"any liquor stores in Perth, WA that carry Dead...",I have a relative travelling home soon who cou...
4,Foursquare Sovereignty UK release?,Anyone any idea when this is releasing? Cause ...

In [116]:
#remove duplicates
rum1.drop_duplicates(keep="first", inplace=True)

C:\Users\Jing Cheng\AppData\Local\Temp\ipykernel_10860\3885480708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rum1.drop_duplicates(keep="first", inplace=True)

In [117]:
# remove all null, removed or deleted in dataframe, replace nan with empty string
rum1 = rum1.replace({"[removed]": np.NaN})
rum1 = rum1.replace({"[deleted]": np.NaN})
rum1 = rum1.replace(np.nan, "", regex=True)

In [118]:
#clean the titles and selftext before combining
rum1 = rum1.apply(regex_cleaning, axis=1)

In [119]:
#labelling each row in rum; 2
rum1['origin'] = 2

In [120]:
#combine selftext and title to form a new column alltext
rum1['alltext'] = rum1['title'] + " " + rum1['selftext']

In [121]:
rum1.shape

(7762, 4)

#### 3.3.3.3 Combine both dataframes

In [122]:
#combine both dataframes together
whiskeyrum = pd.concat(objs=[whiskey1, rum1], axis=0)
#removal of duplicates found
whiskeyrum.drop_duplicates(subset=['selftext'], keep="first",inplace=True)
#reset index
whiskeyrum.reset_index(inplace=True, drop=True)
whiskeyrum.head(50)

,title,selftext,origin,alltext
0,Facts and Truth,,1,Facts and Truth
1,Dads old bottles,My father passed away in he had stopped drinki...,1,Dads old bottles My father passed away in he ...
2,Opinions on Singleton Luscious Nectar,I am thinking about buying this one its also o...,1,Opinions on Singleton Luscious Nectar I am th...
3,Classic Examples of Whiskey categories Suggest...,I ve been drinking whiskey for over decades bu...,1,Classic Examples of Whiskey categories Suggest...
4,Buffalo Trace good buy,Found some Buffalo Trace for ml here in Vegas ...,1,Buffalo Trace good buy Found some Buffalo Tra...
5,The madness continues,So I was at Total Wine picking up a bottle of ...,1,The madness continues So I was at Total Wine p...
6,Old Fashioned Cocktails Whiskey Sour,Processing video xiiurmcyb Classic Whiskey So...,1,Old Fashioned Cocktails Whiskey Sour Processi...
7,Ohio folks,Is it true that Ohio has some law agreement wi...,1,Ohio folks Is it true that Ohio has some law a...
8,Total Wine More Member Program,Not sure if this is the right place to ask thi...,1,Total Wine More Member Program Not sure if th...
9,Parting gift suggestions,Hey guys I m leaving work and moving on to som...,1,Parting gift suggestions Hey guys I m leaving...
10,Willett Family Reserve Rye yr,I just received a bottle of Willett Rye and do...,1,Willett Family Reserve Rye yr I just received ...
11,Bottle didn t have any plastic wrap around the...,I recently bought a bottle of ogd and was abou...,1,Bottle didn t have any plastic wrap around the...
12,To anyone living in Japan,I was honestly wondering what blantons takara ...,1,To anyone living in Japan I was honestly wond...
13,E H Taylor Barrel Proof Rye Release,Saw online E H Taylor is rolling out a BP rye ...,1,E H Taylor Barrel Proof Rye Release Saw onlin...
14,Classy upscale whiskey glasses decanter,Looking for options on a great set of whiskey ...,1,Classy upscale whiskey glasses decanter Looki...
15,Figured I d post my Whiskey shelf of things I ...,Small part of the collection but some of the t...,1,Figured I d post my Whiskey shelf of things I ...
16,Tater post my apologies,College student from SC here Went to a friend ...,1,Tater post my apologies College student from ...
17,Need help with blind tasting,I went into labor five weeks early so I wasn t...,1,Need help with blind tasting I went into labor...
18,Recommendations for Distilleries near Gatlinbu...,I m visiting Gatlinburg this summer any recomm...,1,Recommendations for Distilleries near Gatlinbu...
19,Looking for a small flask for my father Any su...,Hi there I m looking for a flask for my father...,1,Looking for a small flask for my father Any su...
20,Mizunara aged Japanese whiskies,What are some Japanese whiskies aged in Mizuna...,1,Mizunara aged Japanese whiskies What are some...
21,Double Platinum,Proud to say my website All American Whiskey j...,1,Double Platinum Proud to say my website All A...
22,Low No alcohol whiskeys,Has anyone tried any of the low or no alcohol ...,1,Low No alcohol whiskeys Has anyone tried any ...
23,Bourbon vs scotch,What is going to be sweeter I ve been doing so...,1,Bourbon vs scotch What is going to be sweeter ...
24,Whiskey recommendation graduation,I am looking for a must have unique whiskey to...,1,Whiskey recommendation graduation I am looking...
25,What s a good whiskey to celebrate a new job,I just got cleared for a job at one of my drea...,1,What s a good whiskey to celebrate a new job ...
26,Selling premium Whiskeys,I am looking to sell a bunch of Bourbons Rye w...,1,Selling premium Whiskeys I am looking to sell ...
27,Graduation Whiskey Advice,Hey all I m about to graduate university and i...,1,Graduation Whiskey Advice Hey all I m about to...
28,Branching out,Being a year old college kid I ve tried most m...,1,Branching out Being a year old college kid I v...
29,Whiskey without malted barley,So I fell in love with bourbon about years ago...,1,Whiskey without malted barley So I fell in lov...
30,I mixed a glass of water with whiskey what are...,I have tried alcohol for the first time I used...,1,I mixed a glass of water with whiskey what are...
31,Rare whiskey release Pennsylvania,Pa used to do a whiskey release every third We...,1,Rare whiskey release Pennsylvania Pa used to d...
32,Lockable Decanter,Does anyone know of a not so expensive lockabl...,1,Lockable Decanter Does anyone know of a not s...
33,What s your sleeper bottle,Bottle that you can actually find and after th...,1,What s your sleeper bottle Bottle that you ca...
34,Single Malt,Hi guys I m a novice when it comes to single m...,1,Single Malt Hi guys I m a novice when it comes...
35,Missing plastic seal on Russell s Reserve,Just bought a bottle of Russell s reserve year...,1,Missing plastic seal on Russell s Reserve Jus...
36,Obsessed,Started the bourbon hunt in the last two month...,1,Obsessed Started the bourbon hunt in the last ...
37,If you open a bottle with a cork and don t rea...,Should you worry about losing liquid through e...,1,If you open a bottle with a cork and don t rea...
38,Buffalo Trace self promotion,Serious question here why is this subreddit so...,1,Buffalo Trace self promotion Serious question...
39,Gift,So I was thinking about getting my uncle a Hib...,1,Gift So I was thinking about getting my uncle ...
40,Infinity Bottles,Started a peated unpeated infinity bottle and ...,1,Infinity Bottles Started a peated unpeated inf...
41,Anybody ever order from teas ware,Killer deals and free shipping just want to ma...,1,Anybody ever order from teas ware Killer deal...
42,Aging Whiskey Help,I am attempting to dip my hands into cheaply a...,1,Aging Whiskey Help I am attempting to dip my h...
43,Shots of Blanton s,So I m a bartender and last night this lady ca...,1,Shots of Blanton s So I m a bartender and last...
44,Duty Free Heathrow,Anybody ever score anything interesting at Dut...,1,Duty Free Heathrow Anybody ever score anythin...
45,Banana pancake blend,I thought I remember seeing some people blendi...,1,Banana pancake blend I thought I remember see...
46,Drinking responsibly while loving the heck out...,Honest question here I m not a guy that s a he...,1,Drinking responsibly while loving the heck out...
47,Suggestions,Hey guys I m new to whiskey and my first bottl...,1,Suggestions Hey guys I m new to whiskey and m...
48,Seeking gift for SO Birthday,Hi all My SO s birthday is rapidly approaching...,1,Seeking gift for SO Birthday Hi all My SO s bi...
49,Going to be visiting Tennesee around south of ...,I am from Alabama and I am looking to pick up ...,1,Going to be visiting Tennesee around south of ...

In [123]:
whiskeyrum.shape

(5696, 4)

In [124]:
#saving to csv
whiskey1.to_csv('../datasets/whiskey1.csv', index=False)
rum1.to_csv('../datasets/rum1.csv', index=False)
whiskeyrum.to_csv('../datasets/whiskeyrum.csv', index=False)